from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


def create_mock_pptx(
    *,
    output_path: Path,
    combined_key: str,
    image_paths: list[Path],
    xlsx_path: Path | None,
) -> None:
    """
    Replace this function with the real python-pptx implementation.
    The current mock creates a small valid PPTX containing job metadata.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt

        presentation = Presentation()
        slide = presentation.slides.add_slide(presentation.slide_layouts[6])

        title_box = slide.shapes.add_textbox(Inches(0.7), Inches(0.6), Inches(8.7), Inches(0.7))
        title = title_box.text_frame.paragraphs[0]
        title.text = f"Mock PPTX - {combined_key}"
        title.font.bold = True
        title.font.size = Pt(28)

        body_box = slide.shapes.add_textbox(Inches(0.8), Inches(1.7), Inches(8.5), Inches(3.2))
        frame = body_box.text_frame
        lines = [
            "This is a mock file generated by the FastAPI backend.",
            f"TIF image count: {len(image_paths)}",
            f"XLSX uploaded: {'yes' if xlsx_path else 'no'}",
            "Replace app/pptx_generator.py with the real python-pptx layout logic.",
        ]
        for index, line in enumerate(lines):
            paragraph = frame.paragraphs[0] if index == 0 else frame.add_paragraph()
            paragraph.text = line
            paragraph.font.size = Pt(16)

        presentation.save(output_path)
    except Exception:
        _create_minimal_pptx(output_path, combined_key, len(image_paths), xlsx_path is not None)


def _create_minimal_pptx(output_path: Path, combined_key: str, image_count: int, has_xlsx: bool) -> None:
    escaped_key = _xml_escape(combined_key)
    escaped_xlsx = "yes" if has_xlsx else "no"

    files = {
        "[Content_Types].xml": """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  <Override PartName="/ppt/slides/slide1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>
</Types>""",
        "_rels/.rels": """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>""",
        "ppt/presentation.xml": """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <p:sldIdLst><p:sldId id="256" r:id="rId1"/></p:sldIdLst>
  <p:sldSz cx="9144000" cy="5143500" type="screen16x9"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>""",
        "ppt/_rels/presentation.xml.rels": """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/>
</Relationships>""",
        "ppt/slides/slide1.xml": f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
  <p:cSld><p:spTree>
    <p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
    <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
    <p:sp><p:nvSpPr><p:cNvPr id="2" name="Mock title"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr/>
      <p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:r><a:t>Mock PPTX - {escaped_key}</a:t></a:r></a:p><a:p><a:r><a:t>TIF image count: {image_count}, XLSX uploaded: {escaped_xlsx}</a:t></a:r></a:p></p:txBody>
    </p:sp>
  </p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>""",
    }

    with ZipFile(output_path, "w", ZIP_DEFLATED) as archive:
        for name, content in files.items():
            archive.writestr(name, content)


def _xml_escape(value: str) -> str:
    return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
